/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   index.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

export {AuthorizationMethod} from './src/AuthorizationMethod.js';
export {
  METHOD_BASIC,
  METHOD_NTLM,
  METHOD_DIGEST,
  METHOD_OAUTH1,
  METHOD_OAUTH2,
} from './src/Utils.js';
