/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/DigestMethodMixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html} from 'lit-element';

import {notifyChange} from './Utils.js';

export {DigestMethodMixin};


/**
 * Mixin that adds support for Digest method computations
 */
declare function DigestMethodMixin(superClass: any): any;
