/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/Oauth1MethodMixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html} from 'lit-element';

import {notifyChange, normalizeType} from './Utils.js';

export {Oauth1MethodMixin};


/**
 * Mixin that adds support for OAuth 1 method computations
 */
declare function Oauth1MethodMixin(superClass: AuthorizationBase|null): any;
